// FILE: D:/TRAVAIL/M2/Robotique_Avancee/SVN_partie_info/Vision/Diagrams_argoUML/Generated_code//AbstractVisionModule.cpp

#include "AbstractVisionModule.h"


    /* {src_lang=cpp}*/


    // Operations

void AbstractVisionModule::acquireFrame()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-1cd96a5f:12de6c68c79:-8000:0000000000000A17 begin
{
    
}
// section -64--88-56-1-1cd96a5f:12de6c68c79:-8000:0000000000000A17 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool AbstractVisionModule::Setup()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B24 begin
{
    return false;
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B24 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void AbstractVisionModule::Run()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B26 begin
{
    
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B26 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
