// FILE: D:/TRAVAIL/M2/Robotique_Avancee/SVN_partie_info/Vision/Diagrams_argoUML/Generated_code//Camera.cpp

#include "Camera.h"


    /* {src_lang=cpp}*/


    // Operations

void Camera::Calibrate()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B8F begin
{
    
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B8F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Camera::SaveMatrices()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B94 begin
{
    
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B94 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Camera::LoadMatrices()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B96 begin
{
    
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B96 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
