// FILE: D:/TRAVAIL/M2/Robotique_Avancee/SVN_partie_info/Vision/Diagrams_argoUML/Generated_code//VideoSource.cpp

#include "VideoSource.h"


    /* {src_lang=cpp}*/


    // Operations

int VideoSource::grab()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B2E begin
{
    return 0;
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B2E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VideoSource::retrieve()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B30 begin
{
    return 0;
}
// section -64--88-56-1-335d9a63:12de6f88fde:-8000:0000000000000B30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
